/* eslint-disable no-console */
import { fileURLToPath } from 'node:url';
import { dirname, resolve, join } from 'node:path';
import { readFileSync, writeFileSync } from 'node:fs';
import { generateDirectusTypes } from 'directus-sdk-typegen';
import dotenv from 'dotenv';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = resolve(__dirname, '../../'); // Go up two levels to project root

function postProcessTypes(outputPath) {
	const disclaimer =
		'// @ts-nocheck\n/**\n * This file is auto-generated by the Directus type generator.\n * Do not edit this file manually. Regenerate types from Directus schema instead.\n */\n\n';
	let content = disclaimer + readFileSync(outputPath, 'utf-8');

	// Make FormSubmissionValue.id optional (generated as required, but should be optional for new submissions)
	content = content.replace(
		/(interface FormSubmissionValue \{[\s\S]*?\/\*\* @primaryKey \*\/\s*\n\s*)id: string/,
		'$1id?: string',
	);

	writeFileSync(outputPath, content, 'utf-8');
}

async function generateTypes() {
	const directusUrl = process.env.DIRECTUS_URL;
	const directusToken = process.env.DIRECTUS_ADMIN_TOKEN;

	if (!directusUrl || !directusToken) {
		console.error('Error: DIRECTUS_URL or DIRECTUS_ADMIN_TOKEN is missing in the .env file.');
		process.exit(1);
	}

	try {
		const outputPath = join(projectRoot, 'nuxt', 'shared', 'types', 'schema.ts');

		// Log the path to help debug in case of errors
		console.log('Attempting to write to:', outputPath);

		await generateDirectusTypes({ outputPath, directusUrl, directusToken });
		postProcessTypes(outputPath);
		console.log('Types successfully generated!');
	} catch (error) {
		console.error('Failed to generate types:', error);
		console.error('Current directory:', __dirname);
		console.error('Project root:', projectRoot);
		process.exit(1);
	}
}

generateTypes();
