import { config } from 'dotenv';
import { generateDirectusTypes } from 'directus-sdk-typegen';
import { readFileSync, writeFileSync } from 'fs';

config();

function postProcessTypes(outputPath: string): void {
	const disclaimer =
		'// @ts-nocheck\n/**\n * This file is auto-generated by the Directus type generator.\n * Do not edit this file manually. Regenerate types from Directus schema instead.\n */\n\n';
	let content = disclaimer + readFileSync(outputPath, 'utf-8');
	// Make FormSubmissionValue.id optional (generated as required, but should be optional for new submissions)
	content = content.replace(
		/(interface FormSubmissionValue \{[\s\S]*?\/\*\* @primaryKey \*\/\s*\n\s*)id: string/,
		'$1id?: string',
	);
	writeFileSync(outputPath, content, 'utf-8');
}

async function generateTypes() {
	const directusUrl = process.env.NEXT_PUBLIC_DIRECTUS_URL;
	const directusToken = process.env.DIRECTUS_ADMIN_TOKEN;

	if (!directusUrl || !directusToken) {
		console.error('Error: NEXT_PUBLIC_DIRECTUS_URL or DIRECTUS_ADMIN_TOKEN is missing in the .env file.');
		process.exit(1);
	}

	const outputPath = './src/types/directus-schema.ts';

	try {
		await generateDirectusTypes({ outputPath, directusUrl, directusToken });
		postProcessTypes(outputPath);
		console.log('Types successfully generated!');
	} catch (error) {
		console.error('Failed to generate types:', error);
	}
}

generateTypes();
