services:
  database:
    image: postgis/postgis:13-master
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=directus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  cache:
    image: redis:6
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  directus:
    image: directus/directus:11.4.1
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b44'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"

      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"

      WEBSOCKETS_ENABLED: "true"

      PUBLIC_URL: "http://localhost:8055"

      # CORS Configuration:
      # Development: It's ok to use "*" or "http://localhost:3000" for local testing
      # Production: Specify exact origins like:
      #  - Single origin: "https://your-domain.com"
      #  - Multiple origins: "https://app.domain.com,https://admin.domain.com"
      # Warning: Using "*" in production is a security risk - always specify allowed origins
      CORS_ENABLED: "true"
      CORS_ORIGIN: "*"

      REFRESH_TOKEN_COOKIE_SECURE: "false"
      REFRESH_TOKEN_COOKIE_SAME_SITE: "lax"
      REFRESH_TOKEN_DOMAIN: "localhost"

      SESSION_COOKIE_SECURE: "false"
      SESSION_COOKIE_SAME_SITE: "lax"
      SESSION_COOKIE_DOMAIN: "localhost"

      EXTENSIONS_PATH: "./extensions"
      EXTENSIONS_AUTO_RELOAD: "true"

      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: "http://localhost:3000,https://www.youtube-nocookie.com,https://player.vimeo.com"
